### ISSUE TITLE
Disposable accepts raw function

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/event-kit#25]
The definition of a `Disposable` given in the readme states:
> Disposables are ... objects that have a `dispose` function on them.

Which matches the Atom implementation that this is emulating, _however_, the actual implementation accepts a raw function as input, and the [`validate()` ](https://github.com/steelbrain/event-kit/blob/61b268d61803acb96d1d8952479cebc0b2135735/src/helpers.js#L6) check allows this.

Either the definition needs to be updated to match the implementation (diverging from the implementation in Atom this is emulating!), or the implementation should be fixed to match the definition.

**Comment by steelbrain** [comment]
This is actually on purpose, for most of the use cases, creating a `Disposable()` is an overkill when being used with CompositeDisposables. Callbacks are wrapped inside Disposables to make sure they are never called more than once, but CompositeDisposable already does that.

Will fix the docs
