### ISSUE TITLE
Missing dependency: Unable to resolve module `assert`

### ISSUE THREAD

**Issue by vtsatskin** [steelbrain/event-kit#31]
Looks like there's a missing module in the package dependencies when running in React Native

```
Unable to resolve module `assert` from `/Users/vt/Code/Logistech/hos-client/node_modules/sb-event-kit/lib/disposable.js`: Module does not exist in the module map or in these directories:
  /Users/vt/Code/Logistech/hos-client/node_modules
```

**Comment by steelbrain** [comment]
That's interesting that you're getting it's not resolved, because `assert` is a [native node.js module](https://nodejs.org/api/assert.html)

**Comment by vtsatskin** [comment]
Could this be because it's not available in the React Native runtime?

**Comment by steelbrain** [comment]
That's entirely possible. In that case, the drop-in replacement [`assert`](https://www.npmjs.com/package/assert) should be installed in your project instead.

Closing as answered but feel free to continue discussing
